a = int(input("Введите A"))
a_1 = a* a
print ("a_1 =", a_1)
a_2 = a_1* a
print ("a_2 =", a_2)
a_3 = a_2* a_2
print ("a_3 =", a_3)
a_4 = a_3* a_2
print ("a_4 =", a_4)
a_5 = a_4* a_3
print ("a_5 =", a_5)
check = pow(a,15)
print ("check =", check)